### ISSUE TITLE
Failed attempt to verify signature and time stamp

### ISSUE THREAD

**Issue by JohnnyJosep** [luisgoncalves/xades4j#103]
This is may signer method and works well.

```java
private static boolean signXAdEST(String folder_in, String folder_out, 
        String fileName) {
        try {

            Document doc = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(new File(folder_in + fileName));
            Element elt = doc.getDocumentElement();
            DOMHelper.useIdAsXmlId(elt);
            KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                    "pkcs12",
                    "C:/Certs/cert.pfx",
                    new FirstCertificateSelector(),
                    new DirectPasswordProvider("SECRET_PASS"),
                    new DirectPasswordProvider("SECRET_PASS"),
                    true);

            Element elemToSign = doc.getDocumentElement();
            DataObjectDesc obj = new DataObjectReference("#" + elemToSign.getAttribute("Id"))
                    .withTransform(new EnvelopedSignatureTransform());
            SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj);

            XadesSigner signer = new XadesTSigningProfile(kdp)
                    .withTimeStampTokenProvider(
                            new AuthenticatedTimeStampTokenProvider(
                                    new DefaultMessageDigestProvider(),
                                    new TSAHttpAuthenticationData(TSA_URL, TSA_USER, TSA_PASS)))
                    .newSigner();

            signer.sign(dataObjs, elemToSign);

            TransformerFactory tFactory = TransformerFactory.newInstance();
            Transformer transformer = tFactory.newTransformer();
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(new File(folder_out + fileName));
            transformer.transform(source, result);

            new File(folder_in + fileName).delete();

            //verifyOut(fileName);

            return true;
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
        return false;
    }
```

Now if I verify the signature with and app like [XolidoSign](https://www.xolido.com) the signature and TimeStamp is valid

And this is my failed attempt to make a method to verify signature and time stamp.

```java
private static boolean verifyXAdEST(String folder, String file) {
        try {
            FileSystemDirectoryCertStore store = new FileSystemDirectoryCertStore("C:/Certs");
            FileInputStream fis = new FileInputStream("C:/Certs/cert.pfx");
            KeyStore ks = KeyStore.getInstance("pkcs12");
            ks.load(fis, "SECRET_PASS".toCharArray());                         
            fis.close();            
            CertificateValidationProvider provider = new PKIXCertificateValidationProvider(
                    ks,
                    false, 
                    store.getStore());
            
            XadesVerifier verifier = new XadesVerificationProfile(provider)
                    .newVerifier();

            Document doc = DocumentBuilderFactory
                    .newInstance()
                    .newDocumentBuilder()
                    .parse(new File(folder + file));
            
            doc.getDocumentElement().normalize();
            
            Element sig = (Element)doc.getElementsByTagName("ds:Signature").item(0);

            XAdESVerificationResult result = verifier.verify(
                    sig, 
                    null, 
                    new XadesFormatExtenderProfile().getFormatExtender(),
                    XAdESForm.T);

            Collection<SignatureTimeStampProperty> timestamps = result
                    .getPropertiesFilter()
                    .getOfType(SignatureTimeStampProperty.class);
            String res = "Form: " + result.getSignatureForm() + "<br/>"
                    + "Algorithm: " + result.getSignatureAlgorithmUri() + "<br/>"
                    + "Signed data size: " + result.getSignedDataObjects().size() + "<br/>"
                    + "Qualifying size: " + result.getQualifyingProperties().all().size() + "<br/>";
            for (SignatureTimeStampProperty stsp : timestamps) {
                res += "TS: " + stsp.getTime() + "<br/>";
            }            
            System.out.println(res);            
            return true;
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }
        return false;
    }
```

But the method returns
`Error: Bad XML signature`

Somebody can help me plz!!
Thanks

**Comment by luisgoncalves** [comment]
Is there any nested exception? what does it say?

As a side note, I'm not sure why you're using the extender, since the origin signature is already XAdES-T

**Comment by JohnnyJosep** [comment]
Ok, sorry. I will explain better and simplify the problem.

```java
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
factory.setNamespaceAware(false);
DocumentBuilder builder = factory.newDocumentBuilder();
Document doc = builder.parse(new InputSource(new FileReader(SIGNED)));

NodeList nl = doc.getElementsByTagNameNS("http://www.w3.og/2000/09/xmldsig#", "Signature");
System.out.println(nl.getLength());//<---- result here is 0
nl = doc.getElementsByTagName("ds:Signature");
System.out.println(nl.getLength());//<---- result here is 1

FileSystemDirectoryCertStore certStore = new FileSystemDirectoryCertStore(CERT);
FileInputStream fis = new FileInputStream(CERT + STORE);
KeyStore ks = KeyStore.getInstance("jks");
ks.load(fis, PASS.toCharArray());
fis.close();

CertificateValidationProvider provider = new PKIXCertificateValidationProvider(
        ks, false, certStore.getStore());
XadesVerificationProfile profile = new XadesVerificationProfile(provider);
Element sigElem = (Element)nl.item(0);
profile.newVerifier().verify(sigElem, null);
```

In the first place, I feel a little useless when I can not select the signature node with the getElementsByTagNameNS method.

On the other hand the exception that throws me is the following.
```
Exception in thread "main" xades4j.xml.unmarshalling.UnmarshalException: Bad XML signature
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:123)
	at com.zertifika.test.Main.verifyBes(Main.java:154)
	at com.zertifika.test.Main.main(Main.java:64)
Caused by: org.apache.xml.security.exceptions.XMLSecurityException: Cannot create a null:null from a http://www.w3.org/2000/09/xmldsig#:Signature element
	at org.apache.xml.security.utils.ElementProxy.guaranteeThatElementInCorrectSpace(ElementProxy.java:255)
	at org.apache.xml.security.utils.ElementProxy.<init>(ElementProxy.java:97)
	at org.apache.xml.security.utils.SignatureElementProxy.<init>(SignatureElementProxy.java:58)
	at org.apache.xml.security.signature.XMLSignature.<init>(XMLSignature.java:379)
	at org.apache.xml.security.signature.XMLSignature.<init>(XMLSignature.java:364)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:120)
	... 2 more
```


I hope I do not waste your time unnecessarily.
Thank you very much

**Comment by luisgoncalves** [comment]
Try setting `.setNamespaceAware(true)`

**Comment by JohnnyJosep** [comment]
If I declare the NodeList as 
```java
NodeList nl = doc.getElementsByTagNameNS("http://www.w3.og/2000/09/xmldsig#", "Signature");
```
The ouptut is:
```
______________________
	Sign
______________________
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
______________________
	Verify
______________________
Exception in thread "main" java.lang.NullPointerException: Signature node not specified
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:107)
	at com.zertifika.test.Main.verifyBes(Main.java:155)
	at com.zertifika.test.Main.main(Main.java:67)
```

And if I declare as 
```java 
nl = doc.getElementsByTagName("ds:Signature");
```
The ouptut is:
```
______________________
	Sign
______________________
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
______________________
	Verify
______________________
Exception in thread "main" xades4j.XAdES4jXMLSigException: Error verifying the signature
	at xades4j.verification.XadesVerifierImpl.doCoreVerification(XadesVerifierImpl.java:285)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:188)
	at com.zertifika.test.Main.verifyBes(Main.java:155)
	at com.zertifika.test.Main.main(Main.java:67)
Caused by: org.apache.xml.security.signature.MissingResourceFailureException: The Reference for URI #root has no XMLSignatureInput
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID root
	at org.apache.xml.security.signature.Manifest.verifyReferences(Manifest.java:412)
	at org.apache.xml.security.signature.SignedInfo.verify(SignedInfo.java:256)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:764)
	at org.apache.xml.security.signature.XMLSignature.checkSignatureValue(XMLSignature.java:696)
	at xades4j.verification.XadesVerifierImpl.doCoreVerification(XadesVerifierImpl.java:278)
	... 3 more
Caused by: org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID root
	at org.apache.xml.security.signature.Reference.calculateDigest(Reference.java:744)
	at org.apache.xml.security.signature.Reference.verify(Reference.java:787)
	at org.apache.xml.security.signature.Manifest.verifyReferences(Manifest.java:334)
	... 7 more
Caused by: org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID root
	at org.apache.xml.security.signature.Reference.dereferenceURIandPerformTransforms(Reference.java:613)
	at org.apache.xml.security.signature.Reference.calculateDigest(Reference.java:718)
	... 9 more
Caused by: org.apache.xml.security.signature.ReferenceNotInitializedException: Cannot resolve element with ID root
Original Exception was org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID root
	at org.apache.xml.security.signature.Reference.getContentsBeforeTransformation(Reference.java:428)
	at org.apache.xml.security.signature.Reference.dereferenceURIandPerformTransforms(Reference.java:606)
	... 10 more
Caused by: org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID root
	at org.apache.xml.security.utils.resolver.implementations.ResolverFragment.engineResolveURI(ResolverFragment.java:81)
	at org.apache.xml.security.utils.resolver.ResourceResolver.resolve(ResourceResolver.java:275)
	at org.apache.xml.security.signature.Reference.getContentsBeforeTransformation(Reference.java:426)
	... 11 more
```

**Comment by JohnnyJosep** [comment]
For more clarity i upload my code here
https://gist.github.com/JohnnyJosep/29cd545db3d0b7abd23279b56d4db194#file-sign-verify-java

**Comment by luisgoncalves** [comment]
You have a typo on the namespace URI (`og` instead of `org`). Other than that, the two options should be equivalent.

I think the problem is that you also need to use `DOMHelper.useIdAsXmlId(elem)` for verification. The ID-named attributes are not assumed as XML IDs by default: https://issues.apache.org/jira/browse/SANTUARIO-312.

**Comment by JohnnyJosep** [comment]
Awesome, everything works correctly.
I update the gist for future reference. [sign-verify.java](https://gist.github.com/JohnnyJosep/29cd545db3d0b7abd23279b56d4db194)

Thanks!!
