### ISSUE TITLE
Error during CounterSignature "Cannot resolve element with ID"

### ISSUE THREAD

**Issue by p4535992** [luisgoncalves/xades4j#139]
Hi, i'm tring to make a  countersignature on my signed xml, here the code i'm been using:
```java
	public byte[] counterSignDocument(
			final File toCounterSignDocument, 
			File keyStoreFile,String keyStoreType,final String keyStorePassword) 
					throws Exception {

		File fileToSign = null;
		boolean isTemp = false;
		try {
			
			fileToSign = new File(toCounterSignDocument.getAbsolutePath());
			
			//PrivateKey pk = privateKey;	
			SigningCertSelector signingCertSelector = new SigningCertSelector() {				
				@Override
				public java.security.cert.X509Certificate selectCertificate(
						List<java.security.cert.X509Certificate> availableCertificates) {
						 return availableCertificates.get(0);				    
				}
			};
			
			KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
					keyStoreType,keyStoreFile.getAbsolutePath(), 
					signingCertSelector, new DirectPasswordProvider(keyStorePassword),
					new DirectPasswordProvider(keyStorePassword), true); 

			//INPUTSTREAM TO XML DOC
		    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		    dbf.setValidating(false);
		    dbf.setIgnoringComments(false);
		    dbf.setIgnoringElementContentWhitespace(true);
		    dbf.setNamespaceAware(true);
		    // dbf.setCoalescing(true);
		    // dbf.setExpandEntityReferences(true);
	        DocumentBuilder db = dbf.newDocumentBuilder();
	        db.setEntityResolver(new DSS5Utils.NullResolver());
	        // db.setErrorHandler( new MyErrorHandler());
			Document doc = db.parse(toCounterSignDocument.openStream());
			
			//CounterSigning
			Element elemToSign = doc.getDocumentElement();
	        XadesBesSigningProfile profile = new XadesBesSigningProfile(kp);
	        final XadesSigner counterSigner = profile.newSigner();
	        profile.withSignaturePropertiesProvider(new SignaturePropertiesProvider()
	        {
	            @Override
	            public void provideProperties(
	                    SignaturePropertiesCollector signedPropsCol)
	            {
	                signedPropsCol.addCounterSignature(new CounterSignatureProperty(counterSigner));
	                signedPropsCol.setSignerRole(new SignerRoleProperty("CounterSignature maniac"));
	            }
	        });
	        XadesSigner signer = profile.newSigner();

	        DataObjectDesc obj1 = new DataObjectReference('#' + elemToSign.getAttribute("Id")).withTransform(new EnvelopedSignatureTransform());
	        SignedDataObjects dataObjs = new SignedDataObjects().withSignedDataObject(obj1);

	        signer.sign(dataObjs, elemToSign);        
	        // get inner signatureElement from doc
	        NodeList signatureList = doc.getElementsByTagNameNS(Constants.SignatureSpecNS, Constants._TAG_SIGNATURE);
	        Element signatureElement = (Element)signatureList.item(signatureList.getLength() - 1);
			XadesSignatureFormatExtender extender = new XadesFormatExtenderProfile().getFormatExtender();
			XMLSignature sig = new XMLSignature(signatureElement, signatureElement.getOwnerDocument().getBaseURI());
			Collection<UnsignedSignatureProperty> usp = new ArrayList<UnsignedSignatureProperty>(1);
			usp.add(new CounterSignatureProperty(counterSigner));
			extender.enrichSignature(sig, new UnsignedProperties(usp));
		    //XML DOC TO INPUTSTREAM			
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			Source xmlSource = new DOMSource(doc);
			Result outputTarget = new StreamResult(outputStream);
			TransformerFactory.newInstance().newTransformer().transform(xmlSource, outputTarget);
			ByteArrayInputStream is = new ByteArrayInputStream(outputStream.toByteArray());			
			return is;		
		} catch (Exception e) {
			throw new Exception(e);
		}finally{
			if(isTemp){
				FileUtils.deleteQuietly(fileToSign);
			}
		}
	}
```
Here the original file "xml_example.xml"
```xml
<?xml version="1.0"?>
<a>
	<test>Hello World !</test>
	<b>
		<g>h</g>
	</b>
	<c d="e">f</c>
</a>
```

and the first signed file "xml_example.signed.xml"
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-907c313af7fdd85e702055ab301d82b1">
<ds:SignedInfo>
	<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
	<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
	<ds:Reference Id="r-id-1" Type="http://www.w3.org/2000/09/xmldsig#Object" URI="#o-id-1">
		<ds:Transforms>
			<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#base64"/>
		</ds:Transforms>
		<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
		<ds:DigestValue>oZncgjDrDSw/vuj4wWt3WuPXMNr1pp0XBEMAuj2y2vU=</ds:DigestValue>
	</ds:Reference>
	<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties" URI="#xades-id-907c313af7fdd85e702055ab301d82b1">
		<ds:Transforms>
			<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></ds:Transforms>
		<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
		<ds:DigestValue>16iB2lJnvw/lDIuwFVI9zd6eAL6auq0yU3OEFSjysoQ=</ds:DigestValue>
	</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue Id="value-id-907c313af7fdd85e702055ab301d82b1">K0gTrqGDtxrO/pZe4t+RHEeG76wH9V/6iWR8oK1y7YuFktoKWtS/Ndc1wfcRvF5YsQFmWsd4W/J4V/YfR3uHAEvega+S1Yn0ByncIkbAtrV2QVT0E/4O9S/zqxpa+BzNG/uEHNkdG2J+BeKsEUbHVQDGsMSZoMKOTVpHapqtebAfqKy6z4ZqpaE/jAAxI4pn1U9WH8f3pFz2eMmbJrCDE3JvLOqLhCaSCER369BDQhzjpmQkJ/h+Ty329IOY2ych8lzUZSZ2O9H+PxJqszMdgVKU90BJX0FVB3Q49P2SohDie153ZW0yr3NbFOow6M9cBTWoI0Hn2rBFPnlalge7mw==</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>MIIDZzCCAk+gAwIBAgIEElsWczANBgkqhkiG9w0BAQsFADBkMQswCQYDVQQGEwJJVDEPMA0GA1UECBMGQXJlenpvMRAwDgYDVQQHEwdBcmV6enpvMQ0wCwYDVQQKEwRBT082MQ0wCwYDVQQLEwRBT082MRQwEgYDVQQDEwtNYXJjbyBUZW50aTAeFw0xNzEyMDkyMDAyMDhaFw0yNzEyMDcyMDAyMDhaMGQxCzAJBgNVBAYTAklUMQ8wDQYDVQQIEwZBcmV6em8xEDAOBgNVBAcTB0FyZXp6em8xDTALBgNVBAoTBEFPTzYxDTALBgNVBAsTBEFPTzYxFDASBgNVBAMTC01hcmNvIFRlbnRpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhJCqKFWrqHqBSC+6RcGXP0PxiEcnudOlxLjALmoeGnlN43gNTkh4oUbmdoAgTt+klcaWpahsZr2NewKrz6Ksx8Xr9kcup/at/IylGaVsLVW+ZIEXSzzehX/VV7zCtEmVP/gMa9GY7c0SywCt6ddLfpeJlhJfZhSzbRawD2sVsmq4xMMFX5V3sVbfqEPwOfq7UBhWTLLQ8drp/W2MuKWi/uLFvS9IqTlYJegrciSIIS0rXL9GelPquqib8trgrDwwhdwBxmtBHdR4uwJgPtnidsmbWEiBZ5iYIO1Nc5GxNvzp/UczQTraeldcgV69jH6wwi/6lUBSf5muh+D0W8ZTbQIDAQABoyEwHzAdBgNVHQ4EFgQUq44r/W1Ro0gfiipa23Uf9ET79FEwDQYJKoZIhvcNAQELBQADggEBAEaYx6TKi+HoQJHxFLe+ebomPfgO/eM0bA8gqbpN3LoovEHm0znPbOEyuZ1jfH7U5JM7xAQ+dRrlkRN6373IAYe7WkPoAacQwGKyy0xzIyFvtdXZ+cISzQ/Y67qiC40L4evsI+KxZoOiaUQg8bh6+2TlLcGXeb9NFab4EjFhOw0aQ8f2J8ULOzHNHE58ZNaduK9SsRHVBqIaZuV2e1KTeFHZvF5IJwRmtMAfe+TKHmy3K+AhWym+BZmBrD/LdbLBq0Q9myoQ7gJYQNhe+dpMjKrNx3H7VQO19Hny/gew7i7u+X+7/r4Ib7isw8oYhfj2YOTiDAPQl/vX/2ABoPJmrds=</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
<ds:Object>
<xades:QualifyingProperties xmlns:xades="http://uri.etsi.org/01903/v1.3.2#" Target="#id-907c313af7fdd85e702055ab301d82b1">
<xades:SignedProperties Id="xades-id-907c313af7fdd85e702055ab301d82b1">
<xades:SignedSignatureProperties>
<xades:SigningTime>2017-12-09T22:51:48Z</xades:SigningTime>
<xades:SigningCertificateV2>
	<xades:Cert>
		<xades:CertDigest>
		<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
		<ds:DigestValue>9VlKasMZ1qcwppji/2+vKxcgIk0=</ds:DigestValue>
		</xades:CertDigest>
		<xades:IssuerSerialV2>MHAwaKRmMGQxCzAJBgNVBAYTAklUMQ8wDQYDVQQIEwZBcmV6em8xEDAOBgNVBAcTB0FyZXp6em8xDTALBgNVBAoTBEFPTzYxDTALBgNVBAsTBEFPTzYxFDASBgNVBAMTC01hcmNvIFRlbnRpAgQSWxZz</xades:IssuerSerialV2>
	</xades:Cert>
</xades:SigningCertificateV2>
</xades:SignedSignatureProperties>
<xades:SignedDataObjectProperties>
<xades:DataObjectFormat ObjectReference="#r-id-1"><xades:MimeType>application/octet-stream</xades:MimeType></xades:DataObjectFormat>
</xades:SignedDataObjectProperties>
</xades:SignedProperties>
</xades:QualifyingProperties>
</ds:Object>
<ds:Object Id="o-id-1">PD94bWwgdmVyc2lvbj0iMS4wIj8+DQo8YT4NCgk8dGVzdD5IZWxsbyBXb3JsZCAhPC90ZXN0Pg0KCTxiPg0KCQk8Zz5oPC9nPg0KCTwvYj4NCgk8YyBkPSJlIj5mPC9jPg0KPC9hPg==</ds:Object>
</ds:Signature>
```

At the piece of code `signer.sign(dataObjs, elemToSign); ` i get thi exception:
```
Caused by: org.apache.xml.security.utils.resolver.ResourceResolverException: Cannot resolve element with ID id-907c313af7fdd85e702055ab301d82b1
	at org.apache.xml.security.utils.resolver.implementations.ResolverFragment.engineResolveURI(ResolverFragment.java:81)
	at org.apache.xml.security.utils.resolver.ResourceResolver.resolve(ResourceResolver.java:288)
	at org.apache.xml.security.signature.Reference.getContentsBeforeTransformation(Reference.java:435)
	... 11 more
```

Not sure if it's is a possible bug or i make something wrong with the configuration.
The xml is not signed with xade4j but with another java code, so maybe it's just that it make it fail

 I use the the 1.4.1-SNAPSHOT version.

Greetings.

**Comment by luisgoncalves** [comment]
You question is a bit confusing, because you say that you want to add a counter signature to an existing file, but you're using a XadesSigner and explicitly calling sign, resulting in a new enveloped signature.

Anyway, since Apache Santuario 1.5.0 (http://santuario.apache.org/java150releasenotes.html) the element Ids are not used for lookup; it just delegates to DOM API. This means you should register the Id as XML ID. You can use the helper `DOMHelper.useIdAsXmlId` method in xades4j, or other approaches suggested on Santuario release notes.

I'm not sure what you're trying to accomplish but to add a counter signature to an existing signature - without validation - you'd only need the code related to the "format extender".

**Comment by p4535992** [comment]
ty very much for the clarification

**Comment by p4535992** [comment]
For anyone have similar issue this seem the right code to use:
```java
public void counterSignDocument(InputStream fileToCounterSign, File keyStoreFile,String keyStoreType,final String keyStorePassword) throws DSSException {
	try{
		//INPUTSTREAM TO XML DOC
		DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		dbf.setValidating(false);
		dbf.setIgnoringComments(false);
		dbf.setIgnoringElementContentWhitespace(true);
		dbf.setNamespaceAware(true);

		DocumentBuilder db = dbf.newDocumentBuilder();
		db.setEntityResolver(new DSS5Utils.NullResolver());

		Document doc = db.parse(fileToCounterSign);

		SigningCertSelector signingCertSelector = new SigningCertSelector() {				
			@Override
			public java.security.cert.X509Certificate selectCertificate(
					List<java.security.cert.X509Certificate> availableCertificates) {
					 return availableCertificates.get(0);				    
			}
		};
		
		KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider(
				keyStoreType,keyStoreFile.getAbsolutePath(), 
				signingCertSelector, new DirectPasswordProvider(keyStorePassword),
				new DirectPasswordProvider(keyStorePassword), true); 	

		BasicSignatureOptionsProvider bop=new BasicSignatureOptionsProvider() {
			public boolean signSigningCertificate() {return false;}
			public boolean includeSigningCertificate() {return true;}
			public boolean includePublicKey() {return true;}
		};
		
		//Profile for CounterSigning
		Element elemToSign = doc.getDocumentElement();
		DOMHelper.useIdAsXmlId(elemToSign);
		
		XadesSigningProfile profile = new XadesBesSigningProfile(kp).withBasicSignatureOptionsProvider(bop);
		
		// Get the specific signature algorithm for the key's algorithm.
		AlgorithmsProviderEx algorithmsProvider = new DefaultAlgorithmsProviderEx();
		Algorithm sigAlgUri = algorithmsProvider.getSignatureAlgorithm("RSA");
		if (null == sigAlgUri)
			throw new NullPointerException("Signature algorithm URI not provided");

		Algorithm canonAlgUri = algorithmsProvider.getCanonicalizationAlgorithmForSignature();
		if (null == canonAlgUri)
			throw new NullPointerException("Canonicalization algorithm URI not provided");

		final String digestAlgUri = algorithmsProvider.getDigestAlgorithmForDataObjsReferences();
		if (null == digestAlgUri)
			throw new NullPointerException("Digest algorithm URI not provided");
		
		profile.withDigestEngineProvider(new MessageDigestEngineProvider() {				
			@Override
			public MessageDigest getEngine(String digestAlgorithmURI) throws UnsupportedAlgorithmException {					
				try {
					return MessageDigest.getInstance("SHA-256");
				} catch (NoSuchAlgorithmException e) {
					 throw new UnsupportedAlgorithmException("","",e);
				}
			}
		});
	
		//EXTENDER	
		XadesSigner counterSigner = profile.newSigner();
		XadesFormatExtenderProfile p = new XadesFormatExtenderProfile();		    	   
		XadesSignatureFormatExtender extender = p.getFormatExtender();
			
		logger.debug("Tag do podpisu:"+elemToSign.getNodeName());		
		XMLSignature sig = new XMLSignature(elemToSign, elemToSign.getOwnerDocument().getBaseURI());		
		
		Collection<UnsignedSignatureProperty> usp = new ArrayList<UnsignedSignatureProperty>(1);
		usp.add(new CounterSignatureProperty(counterSigner));

		extender.enrichSignature(sig, new UnsignedProperties(usp));
		
		//XML DOC TO INPUTSTREAM			
		ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
		Source xmlSource = new DOMSource(doc);
		Result outputTarget = new StreamResult(outputStream);
		TransformerFactory.newInstance().newTransformer().transform(xmlSource, outputTarget);
		ByteArrayInputStream is = new ByteArrayInputStream(outputStream.toByteArray());							
	} catch (Exception e) {
		throw new DSSException(e);
	}
}
```
