### ISSUE TITLE
XadesProfileResolutionException in Android

### ISSUE THREAD

**Issue by luisgoncalves** [luisgoncalves/xades4j#154]
Following [this question in S.O.](https://stackoverflow.com/questions/50392193/creating-new-signer-throws-xadesprofileresolutionexception-android-xades4j), we need to investigate the reason for the exception. Is it actually possible to run xades4j as is on Android?

Full strack trace: https://pastebin.com/DXPG91DV.

Sample Android app: https://github.com/treekt/xadesSigning

>  First choose document xml, next choose certificate and type password. And last step - click sign button... If password is okey and you selected every files then app throw away the XadesProfileResolutionException. And remember about permissions in Android Settings App because in another case app throw UnexpectedJCAException

**Comment by luisgoncalves** [comment]
@treekt can you hard-code some XML and certificate files in the sample itself? Makes it easier to test...

**Comment by treekt** [comment]
I have tried but in Android If i want to get file from resources I get InputStream and thats problem because in Xades4j I have to provide cert path for create KeyingDataProvide etc..

**Comment by luisgoncalves** [comment]
You'd need to create a new class derived from the abstract `KeyStoreKeyingDataProvider`... Anyway, I guess we can go forward with this.

**Comment by jzeferino** [comment]
@treekt witch android version are you running the app?
Its a real device or emulator?

Can you please try to test again with this files and give the output please?

Download the [LG.pfx](https://github.com/luisgoncalves/xades4j/tree/master/src/test/cert/my) and use the password: `mykeypass`
Use [this](https://github.com/luisgoncalves/xades4j/blob/master/src/test/xml/content.xml) xml.

**Comment by treekt** [comment]
It Android 7.0, Huawei P9 Lite, so its real device.
I have added your gradle settings but I have to change buildToolsVersion to 27.0.3.
When I used these files I received this stack trace: https://pastebin.com/DJ0yQyAF
But when I try sign document with my own cert I receive previous stack trace.

In addition I pushed changes to remote.

**Comment by treekt** [comment]
I commented out these lines:
`        if (keyingProvider.getSigningCertificateChain().isEmpty()) {
//            throw new IllegalArgumentException("Nie mozna zainicializowac magazynu kluczy ze sciezki: " + pfxPath);
//        }`

And then above stack trace is absent but again app throw XadesProfileResolutionException
Stack trace: https://pastebin.com/1PiWwHhp

**Comment by jzeferino** [comment]
@treekt any chance for you to share your certificate or a copy of it?
Because when you used the certificate I told you I got the same exception as I you. But I don't get the `XadesProfileResolutionException ` yet, maybe its due to your certificate nature.

**Comment by treekt** [comment]
Unfortunately no because Its certificate from my company.
But XadesProfileResolutionException is throwing with my cert and even from xades4j repo test.
So I think its problem on the side library, not cert.

**Comment by treekt** [comment]
@jzeferino Did you test it from my source code?

**Comment by treekt** [comment]
@jzeferino When I used cert which you told me I got SigningKeyException but after remove this problem I got again XadesProfileResolutionException. You didnt get it ?

**Comment by jzeferino** [comment]
@treekt how did you:  

> but after remove this problem  I got again XadesProfileResolutionException

?

**Comment by treekt** [comment]
I said a few posts above..
I commented out these lines:
`//        if (keyingProvider.getSigningCertificateChain().isEmpty()) {
//            throw new IllegalArgumentException("Nie mozna zainicializowac magazynu kluczy ze sciezki: " + pfxPath);
//        }`

**Comment by jzeferino** [comment]
@treekt after commented the line you told I've got the `xades4j.providers.SigningKeyException: XadesProfileResolutionException`.

Now I will see what I can do with @luisgoncalves.

**Comment by luisgoncalves** [comment]
I've been looking through the stack trace and googling a bit... It seems that Guice uses a lot of reflection (and maybe code generation?) in runtime, which may be the issue. In the stack trace we have:

```
at com.google.inject.internal.cglib.reflect.FastClassEmitter.<init>(FastClassEmitter.java:69)
                     at com.google.inject.internal.cglib.reflect.FastClass$Generator.generateClass(FastClass.java:72)
                     at com.google.inject.internal.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
                     at com.google.inject.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
                     at com.google.inject.internal.cglib.reflect.FastClass$Generator.create(FastClass.java:64)
                     at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:166)

```

Some links:

- https://stackoverflow.com/questions/7812885/does-it-make-sense-to-use-guice-for-android
- https://medium.com/@goofyahead/dependency-injection-in-android-2321f0256756

Could it be that Android (or some security setting?) prevents such operations? I'll try to find more infos...

**Comment by luisgoncalves** [comment]
OK, it it really seems related to byte-code generation: https://github.com/google/guice/wiki/OptionalAOP.

The mention "cglib" in the AOP version, which is part of the code path in the stack trace..

**Comment by luisgoncalves** [comment]
I was looking a bit more into this:
- xades4j depends on Guice multibindings, which depends on Guice (with AOP). 
- Tried including the no-AOP version explicitly but started getting errors on build/tests.

Conclusion so far is: unless there's something that could make AOP/byte code generation work in Android, there isn't a quick fix for the issue at hands.

Other ideas:
- Further investigate the errors with the AOP version
- Change xades4j implementation to not use the Guice multibindings and rely solely on the no-AOP package to see how it goes.

**Comment by treekt** [comment]
I have tried replace default Guice in your library to no-aop version by changing dependendcy
`        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.2.0</version>
            <classifier>no_aop</classifier>
        </dependency>
`
And after that, during signing I got error with JAXB because Android doesnt support this.
Could you try replace xml library another one?

**Comment by luisgoncalves** [comment]
Did you have any issues with upgrading Guice? 
I'm not much into existing XML libraries.. I don't know if there is an easy replacement (with code generation et al to avoid changing a lot in the xades4j source).

**Comment by developerAndroid098** [comment]
@treekt - did you resolve this issue ?

**Comment by lexboss93** [comment]
bump

**Comment by luisgoncalves** [comment]
@lexboss93 this is a tricky one, mostly due to JAXB issues reported by @treekt. The Guice AOP/multibindings problem could probably be worked around by changing the internal DI configuration, but replacing JAXB is a much bigger endeavor.

I'll try to work on the first part (Guice issues) to see if we can at least make some progress.
