### ISSUE TITLE
Problem while verifying SignBes and don't get any error messages

### ISSUE THREAD

**Issue by 7orG** [luisgoncalves/xades4j#156]
Hello Luis,
first of all, congratulations for this amazing job and thank you to make our life easier.

I am trying to verify a XML signed with Xades, but something seems to go wrong when executing the following instruction: 

                                    "XAdESVerificationResult r = v.verify(sigElem, null);"

and I don't get any type of error on console. I've read the whole wiki of the project and many solved issues by you on stackoverflow, git, google, etc, but I don't get any point... I have to tell that this is my first experience with electronic signatures and I may don't understand the whole context.

Here is my signBes() procedure (which I think it works good):

```
    protected void signBes(Document doc) throws Exception {

    	URL url = getClass().getResource("/regmaq/regmaq.properties");
    	String URL_FOLDER = url.getPath();
    	String CERT_FOLDER = getTextValue(URL_FOLDER, "/war", false);
    	CERT = Util.getPropiedad("XADES_DIRECTORIO");
    	PASS = Util.getPropiedad("XADES_PASS");
    	
        Element elem = doc.getDocumentElement();
        DOMHelper.useIdAsXmlId(elem);
        
        KeyingDataProvider kdp = new FileSystemKeyStoreKeyingDataProvider(
                "pkcs12",
                CERT_FOLDER + CERT,
                new FirstCertificateSelector(),
                new DirectPasswordProvider(PASS),
                new DirectPasswordProvider(PASS),
                true);
        
        XadesSigner signer = new XadesBesSigningProfile(kdp).newSigner();              
        
        new Enveloped(signer).sign(elem); 
        
        String DOCSIGNED   = "C:/Cert/Resultat/signed.bes.xml";
        TransformerFactory tFactory = TransformerFactory.newInstance(); 
        Transformer transformer = tFactory.newTransformer(); 
        DOMSource source = new DOMSource(doc);         
        StreamResult result = new StreamResult(new File(DOCSIGNED));        
        transformer.transform(source, result);
        
    }

```
Here is the result of my SignBes:

[signed.bes.xml.zip](https://github.com/luisgoncalves/xades4j/files/2213108/signed.bes.xml.zip)

And the following code is how I am trying to verify the signature:

```
    protected void verifyBes() throws RegmaqException, XAdES4jException {
    	
    	String SIGNED   = "C:/Cert/Resultat/signed.bes.xml";
    	String CERT_FOLDER = "C:/certificados/Certs/";
    	String KEY_STORE = "keystore.jks";

try {
    	DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    	factory.setNamespaceAware(true);
    	DocumentBuilder builder = factory.newDocumentBuilder();
    	Document doc = builder.parse(new InputSource(new FileReader(SIGNED)));

    	NodeList nl = doc.getElementsByTagName("ds:Signature");
    	
    	FileSystemDirectoryCertStore certStore = new FileSystemDirectoryCertStore(CERT_FOLDER);
    	KeyStore ks = null;
    	
    	try (FileInputStream fis = new FileInputStream(CERT_FOLDER + KEY_STORE)) {
    		ks = KeyStore.getInstance("jks");
    		ks.load(fis,"passjks".toCharArray());
    	} catch (CertificateException e) {
			e.printStackTrace();
		} catch (KeyStoreException e) {
			e.printStackTrace();
		}
    	
    	CertificateValidationProvider provider = new PKIXCertificateValidationProvider(
    		ks, false, certStore.getStore());
    	
    	XadesVerificationProfile profile = new XadesVerificationProfile(provider);
    	
    	Element sigElem = (Element)nl.item(0);

    	XadesVerifier v = profile.newVerifier();
    	
    	XAdESVerificationResult r = v.verify(sigElem, null);

       /* Flow stops here and doesn't return any error messages on console*/
    	
    	System.out.println("Signature form: " + r.getSignatureForm());
        System.out.println("Algorithm URI: " + r.getSignatureAlgorithmUri());
        System.out.println("Signed objects: " + r.getSignedDataObjects().size());
        System.out.println("Qualifying properties: " + r.getQualifyingProperties().all().size());
    	
		} catch (XadesProfileResolutionException e) {
			e.printStackTrace();
		} catch (XAdES4jException e) {
			e.printStackTrace();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (SAXException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (NoSuchProviderException e) {
			e.printStackTrace();
		} catch (CertificateException e1) {
			e1.printStackTrace();
		} catch (CRLException e1) {
			e1.printStackTrace();
		} catch (ParserConfigurationException e1) {
			e1.printStackTrace();
		} catch (TransformerConfigurationException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (TransformerFactoryConfigurationError e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (TransformerException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}
```

If you would have any idea or advice about how to solve this, it will be really appreciate.

Thank you so much in advance.

Jorge.

**Comment by 7orG** [comment]
Hello again,

thank you for your answer, you were right, there was an issue related to the libs, so we are one step forward now,  it keeps breaking at the same point "XAdESVerificationResult r = v.verify(sigElem, null);" but this time shows an error message:

```
xades4j.providers.CannotBuildCertificationPathException: Trust anchors KeyStore has no trusted certificate entries
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:228)

```
Which comes from:

```
public ValidationData validate(
            X509CertSelector certSelector,
            Date validationDate,
            Collection<X509Certificate> otherCerts) throws CertificateValidationException, UnexpectedJCAException
    {
        PKIXBuilderParameters builderParams;
        try
        {
            builderParams = new PKIXBuilderParameters(trustAnchors, certSelector);
        } catch (KeyStoreException ex)
        {
            throw new CannotBuildCertificationPathException(certSelector, "Trust anchors KeyStore is not initialized", ex);
        } catch (InvalidAlgorithmParameterException ex)
        {
            throw new CannotBuildCertificationPathException(certSelector, "Trust anchors KeyStore has no trusted certificate entries", ex);
        }
.....
```
so, could we say the error is caused by "CertificationValidationProvider" ???
Because of the certificate ??

Thank you so much!!

Jorge

**Comment by luisgoncalves** [comment]
Now the exception seems clear: do you have any trusted certificate entry on the keystore that you are loading for validation?

```
ks = KeyStore.getInstance("jks");
ks.load(fis,"passjks".toCharArray());
```

https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html

**Comment by 7orG** [comment]
Muito obrigado for your quick answer. As you well said, I listed my keystore and there was only privateKey entries so I added a trustedCertEntry one:

```
C:\certificados\Certs>keytool -v -list -keystore keystore.jks
Introduzca la contraseña del almacén de claves:
Tipo de Almacén de Claves: JKS
Proveedor de Almacén de Claves: SUN

Su almacén de claves contiene 2 entradas

Nombre de Alias: certbueno
Fecha de Creación: 24-jul-2018
Tipo de Entrada: trustedCertEntry
.
.
.
***********************************************
***********************************************

Nombre de Alias: 00000000t persona de la peça de prova (r:q0000000j)
Fecha de Creación: 18-jul-2018
Tipo de Entrada: PrivateKeyEntry
Longitud de la Cadena de Certificado: 3
.
.
.
```
And now I am facing to this problem:

```
xades4j.providers.CannotBuildCertificationPathException: No certificate found matching targetContraints.
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)

```
Which comes from:

```
public class PKIXCertPathBuilderSpi
    extends CertPathBuilderSpi {
.
.
.
try
        {
            targets = CertPathValidatorUtilities.findCertificates(certSelect, paramsPKIX.getBaseParameters().getCertificateStores());
            targets.addAll(CertPathValidatorUtilities.findCertificates(certSelect, paramsPKIX.getBaseParameters().getCertStores()));
        }
        catch (AnnotatedException e)
        {
            throw new ExtCertPathBuilderException(
                "Error finding target certificate.", e);
        }

        if (targets.isEmpty())
        {

            throw new CertPathBuilderException(
                "No certificate found matching targetContraints.");
        }
.
.
.
}
```
It's like it doesn't find any certificate in the store??  :(

**Comment by luisgoncalves** [comment]
That's weird... It seems that the criteria on the "cert selector" (built by the library from the data in the signature) doesn't match any certificate in those lists. It should, because:
- Since `KeyInfo` contains `IssueSerial`, the lib uses that as a criteria to match the signing certificate (https://github.com/luisgoncalves/xades4j/blob/master/src/main/java/xades4j/verification/SignatureUtils.java#L106).
- All the certificates in `KeyInfo` are supplied in "other certs".

Can you try activating cert path builder log? `-Djava.security.debug=certpath` (https://docs.oracle.com/javase/7/docs/technotes/guides/security/troubleshooting-security.html)

**Comment by luisgoncalves** [comment]
Any news on this @7orG ?  Did you solve it?

**Comment by 7orG** [comment]
No, I hold it on, holiday time and we're trying to get a real certificate, it's kind of frustrating.... thank you for asking. I can close the thread if you want

**Comment by AoftionStyle** [comment]
@luisgoncalves 
May I ask might seem like an issue of ...

```
xades4j.providers.CannotBuildCertificationPathException: Trust anchors KeyStore has no trusted certificate entries
        at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:228)
        at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:175)
        at XadesBesVerifier.verifyBes(XadesBesVerifier.java:106)
        at XadesBesVerifyMain.main(XadesBesVerifyMain.java:33)
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:157)
        at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:130)
        at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:222)
        ... 3 more
```

when I wrote part of the code as ...
```
line 101: FileInputStream fis = new FileInputStream(storePath);
line 102: ks = KeyStore.getInstance(storeType);
line 103: ks.load(fis, storePassword.toCharArray());
line 104: provider = new PKIXCertificateValidationProvider(ks, false, certStore);
line 105: XadesVerificationProfile profile = new XadesVerificationProfile(provider);
line 106: XadesVerifier verifier = profile.newVerifier();
line 107: XAdESVerificationResult r = verifier.verify(sigElem, null);
```

**Comment by luisgoncalves** [comment]
@AoftionStyle the error seems clear: the `trustAnchors` key store is empty (or at least doesn't have trusted certificate entries). You need to ensure that cert.jks has some trusted certificate entry which can be used as the root of the certificate path.

**Comment by AoftionStyle** [comment]
> You need to ensure that cert.jks has some trusted certificate entry which can be used as the root of the certificate path.

@luisgoncalves  Thanks, then I took a look ...
As I see, I generated a certificate like this
```
# creating pem
$ openssl req -newkey rsa:2048 -x509 -keyout key.pem -out cert.pem -days 365 
# PKCS12 Certificate
$ openssl pkcs12 -export -in cert.pem -inkey key.pem -out certificate.p12 -name "certificate"
# convert from PKCS12 to JKS
$ keytool -importkeystore -srckeystore certificate.p12 -srcstoretype pkcs12 -destkeystore cert.jks
```
I'm looking what thing went wrong from my instruction.

**Comment by AoftionStyle** [comment]
> Check the docs for keytool: https://docs.oracle.com/en/java/javase/11/tools/keytool.html. You probably want --importcert
I replaced with ...

```
# convert from PKCS12 to JKS
$ keytool -impoercert -file cert.pem  -srcstoretype pkcs12 -destkeystore cert.jks 
```
It works, thanks @luisgoncalves 

Found a thing not surprised, the consequence issue
```
xades4j.providers.CannotBuildCertificationPathException: unable to find valid certification path to requested target
        at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
        at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:175)
        at XadesBesVerifier.verifyBes(XadesBesVerifier.java:142)
        at XadesBesVerifyMain.main(XadesBesVerifyMain.java:33)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
        ... 3 more
```

I have trusted certificate entries, how can solve this clue?
