### ISSUE TITLE
Problem signing using xpath value with here() function

### ISSUE THREAD

**Issue by jvrlic** [luisgoncalves/xades4j#177]
Using xades4j (1.5.0) for XadesBES signature for signing UBL2.1 Invoice that has xpath value
`count(ancestor-or-self::sig:UBLDocumentSignatures | **here()**/ancestor::sig:UBLDocumentSignatures[1]) > count(ancestor-or-self::sig:UBLDocumentSignatures) 
`
and namespace 
`xmlns:sig = urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2`

generate exception that couldn not find function: here

`org.apache.xml.security.exceptions.XMLSecurityRuntimeException: Current Node: [#document: null]
	at org.apache.xml.security.transforms.implementations.TransformXPath$XPathNodeFilter.isNodeInclude(TransformXPath.java:148) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.isVisibleInt(CanonicalizerBase.java:550) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.canonicalizeXPathNodeSet(CanonicalizerBase.java:388) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.engineCanonicalizeXPathNodeSetInternal(CanonicalizerBase.java:348) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.engineCanonicalize(CanonicalizerBase.java:154) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.XMLSignatureInput.updateOutputStream(XMLSignatureInput.java:504) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.XMLSignatureInput.updateOutputStream(XMLSignatureInput.java:486) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.Reference.calculateDigest(Reference.java:746) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.Reference.generateDigestValue(Reference.java:414) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.Manifest.generateDigestValues(Manifest.java:205) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.signature.XMLSignature.sign(XMLSignature.java:628) ~[xmlsec-2.0.9.jar:2.0.9]
	at xades4j.production.SignerBES.sign(SignerBES.java:273) ~[xades4j-1.5.0.jar:na]
	at xades4j.production.SignerBES.sign(SignerBES.java:130) ~[xades4j-1.5.0.jar:na]
	at eRacunWS.signature.Signature.SignInvoice(Signature.java:212) ~[classes/:na]
	at eRacunWS.ubl.documents.InvoiceW.sign(InvoiceW.java:90) ~[classes/:na]
	at eRacunWS.components.ScheduledTasks.sendOutgoingEInvoice(ScheduledTasks.java:72) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_152]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
Caused by: javax.xml.transform.TransformerException: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Could not find function: here
	at org.apache.xml.security.utils.JDKXPathAPI.evaluate(JDKXPathAPI.java:108) ~[xmlsec-2.0.9.jar:2.0.9]
	at org.apache.xml.security.transforms.implementations.TransformXPath$XPathNodeFilter.isNodeInclude(TransformXPath.java:141) ~[xmlsec-2.0.9.jar:2.0.9]
	... 28 common frames omitted
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Could not find function: here
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:400) ~[na:1.8.0_152]
	at org.apache.xml.security.utils.JDKXPathAPI.evaluate(JDKXPathAPI.java:106) ~[xmlsec-2.0.9.jar:2.0.9]
	... 29 common frames omitted
Caused by: javax.xml.transform.TransformerException: Could not find function: here
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.error(XPathParser.java:612) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.FunctionCall(XPathParser.java:1509) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PrimaryExpr(XPathParser.java:1448) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.FilterExpr(XPathParser.java:1347) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1280) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Argument(XPathParser.java:1471) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.FunctionCall(XPathParser.java:1539) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PrimaryExpr(XPathParser.java:1448) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.FilterExpr(XPathParser.java:1347) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1280) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(XPathParser.java:131) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:180) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268) ~[na:1.8.0_152]
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(XPathImpl.java:392) ~[na:1.8.0_152]
	... 30 common frames omitted`

**Comment by luisgoncalves** [comment]
- Is this related to https://stackoverflow.com/questions/52855697/using-xades4j-for-signature-ubl2-1-invoice?
- The XPath transform you mentioned is very similar to the "enveloped signature transform" (https://www.w3.org/TR/xmldsig-core1/#sec-EnvelopedSignature). Is this a coincidence? Could it be replaced by this transform?
- xades4j relies on Apache Santuario for core XML-DSIG processing. I've found this reference regarding the `here()` function: http://santuario.apache.org/java150releasenotes.html. It seems that Santuario won't support `here()` unless those optional dependencies are also added. Maybe you could try pulling those deps into your project directly.

**Comment by jvrlic** [comment]
Problem is resolved including dependence xalan : xalan : 2.7.2. in project pom file.

Thanks,
Josip Vrlić
