### ISSUE TITLE
xades4j.verification.ReferenceValueException: Reference '' can not be validated

### ISSUE THREAD

**Issue by DGoRdriguez** [luisgoncalves/xades4j#185]
I need your help to sign the xml document gives me error in the library xades4j generating the error, "unable to find valid certification path to requested target."

Likewise, reporting it to the DIAN service gives the error: "com.indra.mmdd.signature.exceptions.ValidateException: xades4j.verification.ReferenceValueException: Reference '' can not be validated"

**Comment by luisgoncalves** [comment]
You don't provide any information to troubleshoot the error...

Please search in the issues for "DIAN"; there are already many conversations on how to produce signatures for that purpose, namely:
- https://github.com/luisgoncalves/xades4j/issues/134
- https://github.com/luisgoncalves/xades4j/issues/151

Also, the error you mention:

> unable to find valid certification path to requested target

Sounds more like an error during verification than signing. Do you have a stack trace?

**Comment by DGoRdriguez** [comment]
Hello @luisgoncalves 

unable to find valid certification path to requested target
xades4j.providers.CannotBuildCertificationPathException
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:186)
	at xades4j.verification.VerifierTestBase.verifySignature(VerifierTestBase.java:115)
	at xades4j.verification.VerifierTestBase.verifySignature(VerifierTestBase.java:88)
	at xades4j.verification.XadesVerifierImplTest.testVerifyBES(XadesVerifierImplTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
	... 34 more

**Comment by luisgoncalves** [comment]
So, you are doing a verification after all.. What's the setup you did for `PKIXCertificateValidationProvider` ?

**Comment by DGoRdriguez** [comment]
@luisgoncalves  There I have the problem you should not configure my certificate has extesión .p12

**Comment by luisgoncalves** [comment]
I'm not sure we are talking about the same thing. The error above is during a verification, but on your last comment you mention "my certificate", which seems to be something you'd use during a sign operation.

**Comment by DGoRdriguez** [comment]
@luisgoncalves 
I would like you to help me by checking the xml for the error xades4j.verification.ReferenceValueException: Reference '' can not be validated.

Now validate and the document does not change before and after signing it, the integrity of the document is maintained.

**Comment by DGoRdriguez** [comment]
In the threads that you indicated to me, I do not find a light to solve the error.

**Comment by luisgoncalves** [comment]
IF the service responds that the reference cannot be validated, you're probably building it in the wrong way. How are you doing the signature production to get the final? Can you show the setup of you `XadesSigningProfile` and your `DataObjectReference`s ?
