### ISSUE TITLE
CompleteRevocationRefsDataStructureVerifier and XadesCSigningProfile

### ISSUE THREAD

**Issue by brunovianarezende** [luisgoncalves/xades4j#203]
Hi,

I'm trying to sign a XML document by using XadesCSigningProfile, but I'm getting the exception below:

```
Exception in thread "main" xades4j.properties.data.PropertyDataStructureException: Structure verification failed for property CompleteRevocationRefs: empty CRL reference list
	at xades4j.properties.data.CompleteRevocationRefsDataStructureVerifier.verifyStructure(CompleteRevocationRefsDataStructureVerifier.java:35)
	at xades4j.properties.data.PropertiesDataObjectsStructureVerifier.verifiyPropertiesDataStructure(PropertiesDataObjectsStructureVerifier.java:121)
	at xades4j.production.PropertiesDataObjectsGeneratorImpl.doGenPropsData(PropertiesDataObjectsGeneratorImpl.java:93)
	at xades4j.production.PropertiesDataObjectsGeneratorImpl.genPropsData(PropertiesDataObjectsGeneratorImpl.java:73)
	at xades4j.production.PropertiesDataObjectsGeneratorImpl.generateUnsignedPropertiesData(PropertiesDataObjectsGeneratorImpl.java:64)
	at xades4j.production.SignerBES.sign(SignerBES.java:289)
	at xades4j.production.SignerBES.sign(SignerBES.java:130)
```
I don't have any CRL defined. I might be misunderstand what it means, but am I oblied to have a CRL reference list defined? What if I never issued a CRL? (I hope my questions make sense, because I'm mostly an ignorant on CRLs).

**Comment by brunovianarezende** [comment]
Ok, I just misunderstood how CRL works. I created an empty CRL file and things are working now.
