### ISSUE TITLE
Verifying a freshly generated xades-t signature fails

### ISSUE THREAD

**Issue by danjujan** [luisgoncalves/xades4j#205]
I tried to verify a freshly generated xades-t signature like you do in your [testSignTExclusiveC14NWithoutPolicy](https://github.com/luisgoncalves/xades4j/blob/f67bb00281a5bf9f817d42179380ed77cf1d0509/src/test/java/xades4j/production/SignerTTest.java#L65-L80) and [testVerifyTBES](https://github.com/luisgoncalves/xades4j/blob/f67bb00281a5bf9f817d42179380ed77cf1d0509/src/test/java/xades4j/verification/XadesVerifierImplTest.java#L185-L191) test but I got this error message while verifying the document:

```
xades4j.verification.TimeStampInvalidSignatureException: Verification failed for property 'SignatureTimeStamp': invalid token signature
	at xades4j.verification.TimeStampVerifierBase.getEx(TimeStampVerifierBase.java:114)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:89)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:1)
	at xades4j.verification.QualifyingPropertiesVerifierImpl.verifyProperties(QualifyingPropertiesVerifierImpl.java:59)
	at xades4j.verification.XadesVerifierImpl.getValidationDate(XadesVerifierImpl.java:284)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:186)
	at xades4j.verification.VerifierTestBase.verifySignature(VerifierTestBase.java:109)
	at xades4j.verification.VerifierTestBase.verifySignature(VerifierTestBase.java:86)
	at xades4j.verification.XadesVerifierImplTest.testVerifyTBES(XadesVerifierImplTest.java:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: xades4j.providers.TimeStampTokenTSACertException: cannot validate TSA certificate
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:146)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:71)
	... 31 more
Caused by: xades4j.providers.CannotBuildCertificationPathException: unable to find valid certification path to requested target
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:133)
	... 32 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
	... 33 more
```

When debugging the error message I noticed that your [testVerifyTBES](https://github.com/luisgoncalves/xades4j/blob/f67bb00281a5bf9f817d42179380ed77cf1d0509/src/test/java/xades4j/verification/XadesVerifierImplTest.java#L185-L191) test only works because it verifies not the actual output of [testSignTExclusiveC14NWithoutPolicy](https://github.com/luisgoncalves/xades4j/blob/f67bb00281a5bf9f817d42179380ed77cf1d0509/src/test/java/xades4j/production/SignerTTest.java#L65-L80)  but a [document.signed.t.bes.xml](https://github.com/luisgoncalves/xades4j/blob/master/src/test/xml/document.signed.t.bes.xml) file from 2017 instead. When I replace this file with the output of [testSignTExclusiveC14NWithoutPolicy](https://github.com/luisgoncalves/xades4j/blob/f67bb00281a5bf9f817d42179380ed77cf1d0509/src/test/java/xades4j/production/SignerTTest.java#L65-L80) I get the same error message.

**Comment by luisgoncalves** [comment]
The "certificate validation provider" that is used for the verification tests is configured with a fixed set of certificates / trust anchors. For TSA, the certs/crls in the "gva" folder are added:

https://github.com/luisgoncalves/xades4j/blob/master/src/test/java/xades4j/verification/VerifierTestBase.java#L71

The `testSignTExclusiveC14NWithoutPolicy` test seems to generate signatures with a different TSA configured only on that test (I don't remember why). Those signatures can never be validated by the default setup of `testVerifyTBES`. I think `TestTimeStampTokenProvider` is just for illustration purposes, so I guess you can replace it with the default/GVA and everything should be fine.

NOTE: for GVA also check the readme regarding CRLs: https://github.com/luisgoncalves/xades4j/tree/master/src/test/cert/gva

**Comment by luisgoncalves** [comment]
Please re-open if there are any other issues.
