### ISSUE TITLE
Unknown properties were found

### ISSUE THREAD

**Issue by fplou** [luisgoncalves/xades4j#210]
Hi Luis,

I got an error verifying a document : 

_xades4j.xml.unmarshalling.PropertyUnmarshalException: Unknown properties were found
        at xades4j.xml.unmarshalling.FromXmlUnknownUnsignedSigPropsConverter.convertFromObjectTree(FromXmlUnknownUnsignedSigPropsConverter.java:49)
        at xades4j.xml.unmarshalling.FromXmlUnknownUnsignedSigPropsConverter.convertFromObjectTree(FromXmlUnknownUnsignedSigPropsConverter.java:28)
        at xades4j.xml.unmarshalling.UnmarshallerModule.convertProperties(UnmarshallerModule.java:64)
        at xades4j.xml.unmarshalling.DefaultQualifyingPropertiesUnmarshaller.unmarshalProperties(DefaultQualifyingPropertiesUnmarshaller.java:86)
        at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:179)_

From what I understand this is linked to **UnsignedProperties** tag.
I have added profile.acceptUnknownProperties(true) before to call verify and I got this error :

_xades4j.xml.unmarshalling.PropertyUnmarshalException: Unsupported properties were found
	at xades4j.xml.unmarshalling.FromXmlUnsupportedUSPLimiter.convertFromObjectTree(FromXmlUnsupportedUSPLimiter.java:35)
	at xades4j.xml.unmarshalling.FromXmlUnsupportedUSPLimiter.convertFromObjectTree(FromXmlUnsupportedUSPLimiter.java:1)
	at xades4j.xml.unmarshalling.UnmarshallerModule.convertProperties(UnmarshallerModule.java:64)
	at xades4j.xml.unmarshalling.DefaultQualifyingPropertiesUnmarshaller.unmarshalProperties(DefaultQualifyingPropertiesUnmarshaller.java:86)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:179)_

I am lost in source code. I do not understand exactly why I got these errors.
The first error is thrown from this method in **FromXmlUnknownUnsignedSifPropsConverter** :

    _public void convertFromObjectTree(
            XmlUnsignedSignaturePropertiesType xmlProps,
            QualifyingPropertiesDataCollector propertyDataCollector) throws PropertyUnmarshalException
    {
        List<Object> any = xmlProps.getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs();
        if (any.size() > 0 && !this.acceptUnknown)
            throw new PropertyUnmarshalException("Unknown properties were found", "Unknown");_

And the second errot is thrown from this method in **FromXmlUnsupportedUSPLimiter** :

_class FromXmlUnsupportedUSPLimiter implements UnsignedSigPropFromXmlConv
{
    @Override
    public void convertFromObjectTree(
            XmlUnsignedSignaturePropertiesType xmlProps,
            QualifyingPropertiesDataCollector propertyDataCollector) throws PropertyUnmarshalException
    {
        if (!ObjectUtils.allNull(
        		xmlProps.getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs()))
            throw new PropertyUnmarshalException("Unsupported properties were found", "Unsupported");
    }_

I have tried to ignore FromXmlUnsupportedUSPLimiter but the verification fails now with an empty certificate reference list : 

_xades4j.properties.data.PropertyDataStructureException: Structure verification failed for property CompleteCertificateRefs: empty certificate reference list
	at xades4j.properties.data.BaseCertRefsDataStructureVerifier.verifyStructure(BaseCertRefsDataStructureVerifier.java:41)
	at xades4j.properties.data.PropertiesDataObjectsStructureVerifier.verifiyPropertiesDataStructure(PropertiesDataObjectsStructureVerifier.java:121)
	at xades4j.verification.QualifyingPropertiesVerifierImpl.verifyProperties(QualifyingPropertiesVerifierImpl.java:51)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:215)_

You will find attached to this message the xades data.

Could you provide me with some guidance?

Thanks

Regards

François
[xades_extract_from_ACMT017.zip](https://github.com/luisgoncalves/xades4j/files/5312248/xades_extract_from_ACMT017.zip)

**Comment by luisgoncalves** [comment]
Hello,

Your signature includes properties that are part of extended formats (e.g. `CertificateValues` and `ArchiveTimeStamp`). xades4j doesn't support validation of signatures using extended forms. In addition,

it contains `SigningCertificateV2` which is part of newer versions of XAdES. xades4j only supports XAdES 1.3.2 and 1.4.1.

Sorry, but you won't be able to verify that signature using xades4j.
