### ISSUE TITLE
Verify XAdES-T

### ISSUE THREAD

**Issue by Eros-Kaiser** [luisgoncalves/xades4j#219]
Exception in thread "main" xades4j.verification.TimeStampInvalidSignatureException: Verification failed for property 'IndividualDataObjectsTimeStamp': invalid token signature
	at xades4j.verification.TimeStampVerifierBase.getEx(TimeStampVerifierBase.java:114)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:89)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:1)
	at xades4j.verification.QualifyingPropertiesVerifierImpl.verifyProperties(QualifyingPropertiesVerifierImpl.java:59)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:218)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:459)
	at TestMarven.TestTest.App.verifyT(App.java:369)
	at TestMarven.TestTest.App.main(App.java:409)
Caused by: xades4j.providers.TimeStampTokenTSACertException: cannot validate TSA certificate
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:146)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:71)
	... 6 more
Caused by: xades4j.providers.CannotBuildCertificationPathException: unable to find valid certification path to requested target
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:133)
	... 7 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
	... 8 more

i use xades4j 1.6.0

and sign code is
`	public void XadesT(KeyingDataProvider kp, Document doc) throws IOException, XAdES4jException {

		FileOutputStream output = new FileOutputStream("XAdES-T.xml");
		String refUri;
		Element elementToSign = doc.getDocumentElement();

		if (elementToSign.hasAttribute("Id")) {
			refUri = '#' + elementToSign.getAttribute("Id");
		} else {
			if (elementToSign.getParentNode().getNodeType() != Node.DOCUMENT_NODE) {
				output.close();
				throw new IllegalArgumentException("Element without Id must be the document root.");
			}
			refUri = "";
		}
		XadesSigningProfile tSign = new XadesBesSigningProfile(kp).withTimeStampTokenProvider(TestTimeStampTokenProvider.class);
		XadesSigner tSigner = tSign.newSigner();
		DataObjectDesc objT = new DataObjectReference(refUri).withTransform(new EnvelopedSignatureTransform())
				.withDataObjectTimeStamp();
		XadesSignatureResult resultT = tSigner.sign(new SignedDataObjects(objT), doc.getDocumentElement());
		XMLSignature signatureT = resultT.getSignature();
		Document docsT = signatureT.getDocument();
		XMLUtils.outputDOM(docsT, output);
	}`

verify code is 
`public void verifyT() throws Exception {
		Collection<X509Certificate> certChainList;
		DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
		factory.setNamespaceAware(true);
		DocumentBuilder builder = factory.newDocumentBuilder();
		Document doc = builder.parse(new FileInputStream("XAdES-T.xml"));

		NodeList nl = doc.getElementsByTagNameNS(javax.xml.crypto.dsig.XMLSignature.XMLNS, "Signature");
		Element sigElem = (Element) nl.item(1);
		Element certElem = (Element) sigElem.getElementsByTagName("ds:X509Certificate").item(0);
		byte[] bencoded = javax.xml.bind.DatatypeConverter.parseBase64Binary(certElem.getTextContent());
		InputStream in = new ByteArrayInputStream(bencoded);

		cf = CertificateFactory.getInstance("X.509");
		X509Certificate certSigner = (X509Certificate) cf.generateCertificate(in);
		certChainList = getCertChain(certSigner);

		CertificateValidationProvider provider = null;
		CertStore certStore = null;
		KeyStore ks;

		if (certChainList.size() != 0) {
			X509Certificate[] certChain = new X509Certificate[certChainList.size()];
			certChainList.toArray(certChain);
			CollectionCertStoreParameters params = new CollectionCertStoreParameters(certChainList);
			certStore = CertStore.getInstance("Collection", params);
		} else {
			certStore = new FileSystemDirectoryCertStore("trustStore").getStore();
		}

		try (FileInputStream fis = new FileInputStream("trustStore/clientTrustStore")) {
			ks = KeyStore.getInstance("PKCS12");
			ks.load(fis, "123456".toCharArray());
		}

		provider = new PKIXCertificateValidationProvider(ks, false, certStore);

		XadesVerificationProfile profile = new XadesVerificationProfile(provider);
		XadesVerifier verifier = profile.newVerifier();
		
		String refUri = "";
		if (sigElem.hasAttribute("Id")) {
			refUri = '#' + sigElem.getAttribute("Id");
		} else {
			if (sigElem.getParentNode().getNodeType() != Node.DOCUMENT_NODE) {
				throw new IllegalArgumentException("Element without Id must be the document root.");
			}
			refUri = "";
		}
		SignatureSpecificVerificationOptions options = new SignatureSpecificVerificationOptions().useBaseUri(refUri);
		
		
		/**/
		XadesSignatureFormatExtender formExt = new XadesFormatExtenderProfile().getFormatExtender();
		XAdESVerificationResult r = verifier.verify(sigElem,options,formExt,XAdESForm.T);
		Collection<SignatureTimeStampProperty> timeStamps = r.getPropertiesFilter()
				.getOfType(SignatureTimeStampProperty.class);

		for (SignatureTimeStampProperty ts : timeStamps) {
			System.out.println(ts.getTime());
		}
		System.out.println("Signature form: " + r.getSignatureForm());
		System.out.println("Algorithm URI: " + r.getSignatureAlgorithmUri());
		System.out.println("Signed objects: " + r.getSignedDataObjects().size());
		System.out.println("Qualifying properties: " + r.getQualifyingProperties().all().size());

		for (QualifyingProperty qp : r.getQualifyingProperties().all()) {
			if ("SigningCertificate".equals(qp.getName())) {
				Collection<X509Certificate> certs = ((SigningCertificateProperty) qp).getsigningCertificateChain();
				certs.forEach((cert) -> {
					System.out.println(cert.getSubjectDN());
				});
			} else if ("SigningTime".equals(qp.getName())) {
				System.out.println(
						qp.getName() + ": " + ((SigningTimeProperty) qp).getSigningTime().getTime().toString());
			} else if ("SignatureTimeStamp".equals(qp.getName())) {
				System.out.println(qp.getName() + ": " + ((SignatureTimeStampProperty) qp).getTime().toString());
			} else {
				System.out.println("QP name: " + qp.getName());
			}
		}
	}`
I don't know how I solve this error.

**Comment by luisgoncalves** [comment]
The errors clearly indicate what the problem is:

```
Verification failed for property 'IndividualDataObjectsTimeStamp': invalid token signature
Caused by: xades4j.providers.TimeStampTokenTSACertException: cannot validate TSA certificate
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

The `CertificateValidationProvider` that you configure for verification needs to be able to validate TSA certificates as well. Are you sure that it can validate certificates of timestamp tokens issued by `TestTimeStampTokenProvider`?

**Comment by Eros-Kaiser** [comment]
So now i have another problem is UnsignedSignatureProperties is disappear and IndividualDataObjectsTimeStamp is in signedSignatureProperties tag. Is it wrong right?

**Comment by Eros-Kaiser** [comment]
So now I config something and error change to 
Exception in thread "main" xades4j.verification.TimeStampInvalidSignatureException: Verification failed for property 'SignatureTimeStamp': invalid token signature
	at xades4j.verification.TimeStampVerifierBase.getEx(TimeStampVerifierBase.java:114)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:89)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:1)
	at xades4j.verification.QualifyingPropertiesVerifierImpl.verifyProperties(QualifyingPropertiesVerifierImpl.java:59)
	at xades4j.verification.XadesVerifierImpl.getValidationDate(XadesVerifierImpl.java:284)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:186)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:459)
	at TestMarven.TestTest.App.verifyT(App.java:369)
	at TestMarven.TestTest.App.main(App.java:410)
Caused by: xades4j.providers.TimeStampTokenTSACertException: cannot validate TSA certificate
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:145)
	at xades4j.verification.TimeStampVerifierBase.verify(TimeStampVerifierBase.java:71)
	... 7 more
Caused by: xades4j.providers.CannotBuildCertificationPathException: unable to find valid certification path to requested target
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
	at xades4j.providers.impl.DefaultTimeStampVerificationProvider.verifyToken(DefaultTimeStampVerificationProvider.java:133)
	... 8 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
	... 9 more
It's same root cause?

**Comment by luisgoncalves** [comment]
Seems to be the same problem, but in a different qualifying property, which also contains a timestamp.

**Comment by Eros-Kaiser** [comment]
This is my TestTimeStampTokenProvider class
`	class TestTimeStampTokenProvider extends HttpTimeStampTokenProvider {
		@Inject
		public TestTimeStampTokenProvider(MessageDigestEngineProvider messageDigestProvider) {
			super(messageDigestProvider, new TSAHttpData("http://ts.cartaodecidadao.pt/tsa/server", username,password));
		}
	}`
to sign T but i don't have idea to config validator to validate timestamp to using this service.

**Comment by luisgoncalves** [comment]
You'll need to get the certificate of that TSA (probably documented in the PT CC PKI docs) and add it to that `trustStore` that you are using for validation

**Comment by Eros-Kaiser** [comment]
I don't understand that. You talking about I must have a Certificate to sign (In this case is tsa.p12 file) and another Certificate for TSA right?

**Comment by smartman** [comment]
Usually in production applications you will buy timestamp service from some Trust Service provider. I have been using in eID Easy eIDAS qualified timestamps from https://www.skidsolutions.eu/en/services/time-stamping-service/

**Comment by luisgoncalves** [comment]
@Eros-Kaiser I don't know what the `tsa.p12`file is, since you haven't mentioned it before. I'll try to sum up what I think you're trying to do and what the problem is:

**Sign**
- Create a XAdES-BES signature.
- The signing key/certificate come from `KeyingDataProvider kp` (you don't show how it is built)
- This signature has a single signed data object: the root element of the XML document.
- xades4j is configured to add a timestamp to this data object in the signature. 
- xades4j is configured to use `TestTimeStampTokenProvider` to obtain timestamp tokens, which uses the TSA at `http://ts.cartaodecidadao.pt/tsa/server`.
- Note that timestamp tokens are themselves signed artifacts. The TSA signs it using its private key and should make a certificate available so that timestamp signatures can be verified.

**Verify**
- To fully verify the signature you need trust anchors for: 1) your signing key/certificate 2) the TSA signing key/certificate (assuming those are different, which seems to be the case because the verification fails).
- Those are being added from the keystore in `trustStore/clientTrustStore`
- You also need any intermediate certificates to build the trust path that are not contained in the signature.
- Those are being added from from the `trustStore` folder

My question was: does trustStore/clientTrustStore and trustStore contain all the needed certificates / trust root certificates to build both certification paths (singing certificate + timestamp/TSA certificate).

**Comment by Eros-Kaiser** [comment]
Ok sorry for weasted your time my scope is just sign XAdES-BES & T and verify them by keystore type pkcs12.

I don't know what I should scope the problem for this

`public static void main(String[] args) throws Exception {
		App signObject = new App();
		KeyingDataProvider kp = new FileSystemKeyStoreKeyingDataProvider("PKCS12", "trustStore/tsa.p12",
				new FirstCertificateSelector(), new DirectPasswordProvider("1234"), new DirectPasswordProvider("1234"),
				true);
		signObject.XadesBES(kp, signObject.getXMLDocumentByPath("ScoreReport.xml"));
		signObject.verifyBes(signObject.getXMLDocumentByPath("XAdES-BES.xml"));
		signObject.XadesT(kp, signObject.getXMLDocumentByPath("ScoreReport.xml"));
		signObject.verifyT(signObject.getXMLDocumentByPath("XAdES-T.xml"));
}`

this is kp build

and trustStrore and cert is 
[trustStore.zip](https://github.com/luisgoncalves/xades4j/files/6034603/trustStore.zip)
all cert pass is 1234
clientTrustStore password is 123456

I use tsa.p12 is main for sign cause of this keystore I config extendsion when build to timestamp(I don't know is it relate?)

and this is xml file
[TestTest.zip](https://github.com/luisgoncalves/xades4j/files/6034623/TestTest.zip)
ScoreReport.xml is origin file
XAdES-BES.xml is signed file and can validate
XAdES-T.xml is signed file but can't validate for the error.

thanks for your answer.
Best regards.

**Comment by luisgoncalves** [comment]
I'm not sure how I can be clearer. It seems that you may be confusing some concepts. I had a quick look at the certificates/keys, but I don't understand the mix.

- Which key/certificate pair do you want to use for your signature after all? I.e. who is the "author" of the signature?
- Which Time Stamp Authority (TSA) do you want to use to timestamp your signature?

**Comment by luisgoncalves** [comment]
Did you sort this out?

**Comment by luisgoncalves** [comment]
Please reopen if the issue still stands.
