### ISSUE TITLE
SignatureAppendingStrategy issue with XPath transform

### ISSUE THREAD

**Issue by SamehMahmoud** [luisgoncalves/xades4j#266]
Hi
I want to wrap signature element within` <ext:UBLExtensions>` element using custom `SignatureAppendingStrategy` but it has a problem with xpath transform `"not(//ancestor-or-self::ext:UBLExtensions)"`.
It fires the following exception :

```
Exception in thread "main" java.lang.RuntimeException: Could not resolve the node to a handle
	at org.apache.xml.dtm.ref.DTMManagerDefault.getDTMHandleFromNode(DTMManagerDefault.java:576)
	at org.apache.xpath.XPathContext.getDTMHandleFromNode(XPathContext.java:184)
	at org.apache.xpath.XPath.execute(XPath.java:303)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
	at org.apache.xpath.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:91)
	at org.apache.xpath.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:176)
	at org.apache.xml.security.utils.JDKXPathAPI.evaluate(JDKXPathAPI.java:112)
	at org.apache.xml.security.transforms.implementations.TransformXPath$XPathNodeFilter.isNodeInclude(TransformXPath.java:138)
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.isVisible(CanonicalizerBase.java:489)
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.canonicalizeXPathNodeSet(CanonicalizerBase.java:366)
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.engineCanonicalizeXPathNodeSetInternal(CanonicalizerBase.java:302)
	at org.apache.xml.security.c14n.implementations.CanonicalizerBase.engineCanonicalize(CanonicalizerBase.java:147)
	at org.apache.xml.security.transforms.implementations.TransformC14N.enginePerformTransform(TransformC14N.java:70)
	at org.apache.xml.security.transforms.Transform.performTransform(Transform.java:326)
	at org.apache.xml.security.transforms.Transforms.performTransforms(Transforms.java:267)
	at org.apache.xml.security.signature.Reference.getContentsAfterTransformation(Reference.java:450)
	at org.apache.xml.security.signature.Reference.calculateDigest(Reference.java:708)
	at org.apache.xml.security.signature.Reference.generateDigestValue(Reference.java:417)
	at org.apache.xml.security.signature.Manifest.generateDigestValues(Manifest.java:209)
	at org.apache.xml.security.signature.XMLSignature.sign(XMLSignature.java:782)
	at xades4j.production.SignerBES.sign(SignerBES.java:270)
	at testx.TestXades.main(TestXades.java:258)
```

This is my desired document tree :

```
<Invoice>
    <ext:Extensions>
           <ext:Extension>
                 <ext:ExtensionContent>
                         <sig:UBLDocumentSignatures>
                                 <sac:SignatureInformation>
                                          <ds:Signature>...</ds:Signature>
                                 </sac:SignatureInformation>
                         </sig:UBLDocumentSignatures>
                 </ext:ExtensionContent> 
           </ext:Extension>
    </ext:Extensions>
</Invoice>
```
 **SignatureAppendingStrategy.append()**

```
			@Override
			public void append(Element signatureElement, Node referenceNode) {

				Element ublExtensions = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2","UBLExtensions");
				ublExtensions.setPrefix("ext");

				Element ublExtension = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2","UBLExtension");
				ublExtension.setPrefix("ext");
				ublExtensions.appendChild(ublExtension);
				
				Element extensionURL = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2","ExtensionURI");
				extensionURL.setPrefix("ext");
				Node urlValue = w3cDoc.createTextNode("urn:oasis:names:specification:ubl:dsig:enveloped:xades");
				extensionURL.appendChild(urlValue);
				ublExtension.appendChild(extensionURL);
				
				Element extensionContent = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2","ExtensionContent");
				extensionContent.setPrefix("ext");
				ublExtension.appendChild(extensionContent);
				
				Element ublDocumentSignatures = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2","sig:UBLDocumentSignatures");
				ublDocumentSignatures.setAttribute("xmlns:sac", "urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2");
				ublDocumentSignatures.setAttribute("xmlns:sbc", "urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2");
				extensionContent.appendChild(ublDocumentSignatures);
				
				Element signatureInformation = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2","SignatureInformation");
				signatureInformation.setPrefix("sac");
				ublDocumentSignatures.appendChild(signatureInformation);
				
				Element cbcId = w3cDoc.createElementNS("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2","ID");
				cbcId.setPrefix("cbc");
				Node idValue = w3cDoc.createTextNode("urn:oasis:names:specification:ubl:signature:1");
				cbcId.appendChild(idValue);
				signatureInformation.appendChild(cbcId);
				signatureInformation.appendChild(signatureElement);

				referenceNode.insertBefore(ublExtensions, referenceNode.getFirstChild());
				
			}
```

**DataObjectDesc  :**

```
		DataObjectDesc desc = new DataObjectReference("")
			.withTransform(new XPathTransform("not(//ancestor-or-self::ext:UBLExtensions)"))
			.withTransform(new XPathTransform("not(//ancestor-or-self::cac:Signature)"))
			.withTransform(new XPathTransform("not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])"))
			.withTransform(new xades4j.algorithms.CanonicalXMLWithoutComments());
```

**Comment by luisgoncalves** [comment]
This doesn't seem like a problem in xades4j per-se. Probably something wrong with the XPath expressions vs the element definitions? One thing that caught my eye is the lines where you set the `xmlns` attributes. I think those need to be in a particular namespace (`setAttributeNS("http://www.w3.org/2000/xmlns/", ...)`). Not sure if it is relevant.

I don't know what exactly you're trying to achieve with the XPath transforms - i.e. what you want to sign or exclude from signing - but perhaps changing the way the reference is defined could avoid the XPAth's altogether.

Also, how's the `sign `method being invoked?

**Comment by luisgoncalves** [comment]
Closing due to inactivity; reopen if needed.
